



#+BEGIN_SRC emacs-lisp
(scimax-jupyter-advise)
#+END_SRC

#+RESULTS:

#+BEGIN_SRC emacs-lisp
(scimax-jupyter-org-hydra/body)
#+END_SRC

#+RESULTS:


#+PROPERTY: header-args:jupyter-python  :session jupyter-python-e02181d2ded88ae0d83fa376da2b35aa

#+BEGIN_SRC jupyter-python :results raw
for i in range(3):
    print(i)
#+END_SRC

#+RESULTS:
0
1
2



#+BEGIN_SRC jupyter-python
import numpy as np
np.linspace
#+END_SRC

#+RESULTS:
:RESULTS:
<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>
:END:



#+RESULTS:

#+BEGIN_SRC jupyter-python
np.
#+END_SRC



** plotly

#+BEGIN_SRC jupyter-python
from pycse.plotly import *
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color ="species",
                 size ="petal_length", hover_data=['petal_width'])
fig.show()
#+END_SRC

#+RESULTS:
:RESULTS:
# [goto error]

TypeErrorTraceback (most recent call last)
<ipython-input-8-ddd507e31254> in <module>
      5 fig = px.scatter(df, x="sepal_width", y="sepal_length", color ="species",
      6                  size ="petal_length", hover_data=['petal_width'])
----> 7 fig.show()

~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, *args, **kwargs)
     28         f.write(html)
     29 
---> 30     display(FileLink(fhtml, result_html_suffix=""))
     31 
     32     return Image(pio.to_image(self, "png", engine="kaleido"))

TypeError: 'module' object is not callable
:END:

#+BEGIN_SRC jupyter-python
from pycse.orgmode import *
import matplotlib.pyplot as plt

data = [['x', 'y'], None, [1, 2], [2, 4]]
org.table(data, name='table-data', caption='Data from a python table')

print()

plt.plot([4, 5, 6])
org.figure(plt.savefig('images/a-figure.png'), name='fig:1', caption='A figure in org-mode')
#+END_SRC

#+RESULTS:
:RESULTS:
# [goto error]

AttributeErrorTraceback (most recent call last)
<ipython-input-9-1b87fd9b57c9> in <module>
      3 
      4 data = [['x', 'y'], None, [1, 2], [2, 4]]
----> 5 org.table(data, name='table-data', caption='Data from a python table')
      6 
      7 print()

AttributeError: module 'pycse.orgmode' has no attri [[** plotly

#+BEGIN_SRC jupyter-python
from pycse.plotly import *
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color ="species",
                 size ="petal_length", hover_data=['petal_width'])
fig.show()
#+END_SRC

#+BEGIN_SRC jupyter-python
import pycse.orgmode as org
import matplotlib.pyplot as plt

data = [['x', 'y'], None, [1, 2], [2, 4]]
org.table(data, name='table-data', caption='Data from a python table')

print()

plt.plot([4, 5, 6])
org.figure(plt.savefig('images/a-figure.png'), name='fig:1', caption='A figure in org-mode')
#+END_SRC


*** test pyces
#+BEGIN_SRC jupyter-python
from pycse.plotly import *

import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color = "species", size = "petal_length", hover_data=['petal_width'])

fig.show()

#+END_SRC

#+RESULTS:
:RESULTS:
# [goto error]

TypeErrorTraceback (most recent call last)
<ipython-input-1-0de3666b2768> in <module>
      5 fig = px.scatter(df, x="sepal_width", y="sepal_length", color = "species", size = "petal_length", hover_data=['petal_width'])
      6 
----> 7 fig.show()

~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, *args, **kwargs)
     28         f.write(html)
     29 
---> 30     display(FileLink(fhtml, result_html_suffix=""))
     31 
     32     return Image(pio.to_image(self, "png", engine="kaleido"))

TypeError: 'module' object is not callable
:END:






















]] bute 'table'
:END:


*** test pyces
#+BEGIN_SRC jupyter-python
from pycse.plotly import *

import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color = "species", size = "petal_length", hover_data=['petal_width'])

fig.show()

#+END_SRC

#+RESULTS:
:RESULTS:
# [goto error]

TypeErrorTraceback (most recent call last)
<ipython-input-1-0de3666b2768> in <module>
      5 fig = px.scatter(df, x="sepal_width", y="sepal_length", color = "species", size = "petal_length", hover_data=['petal_width'])
      6 
----> 7 fig.show()

~/.local/lib/python3.8/site-packages/pycse/plotly.py in myshow(self, *args, **kwargs)
     28         f.write(html)
     29 
---> 30     display(FileLink(fhtml, result_html_suffix=""))
     31 
     32     return Image(pio.to_image(self, "png", engine="kaleido"))

TypeError: 'module' object is not callable
:END:























